name: push-master
on:
  push:
    branches:
    - master
jobs:
  vue-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache NPM
      uses: actions/cache@v1
      with:
        path: node_modules
        key: node-${{ runner.os }}-${{ hashFiles('package.json') }}

    - name: Install packages
      run: npm install

    - name: Build static pages
      run: npm run build

    - name: Commit changes to production
      run: |
        mkdir ~/production
        cd ~/production
        git clone https://github.com/GravitLauncher/WikiProduction
        cd WikiProduction
        rm -rf !("CNAME"|".git/")
        cp -r $GITHUB_WORKSPACE/dist/ ./
        git commit -m "Autoupdate from source repo"
        git push